PR1
Benjail/Unity.Game-1 pull request #4
Opened 2019-10-19 07:14 UTC by Benjail

2019-10-22 10:03 UTC, HolyMonkey commented
Удали TextMeshPro из проекта (он захламляет PR). Откажись от именования файлов на русском (у тебя сцены так названы)

2019-11-04 16:29 UTC, HolyMonkey commented
Откажись от именования файлов на русском. У тебя всё ещё есть они в проекте

2019-11-04 16:33 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +    //public Chest Chest;
Мы не храним код в комментариях

2019-11-04 16:33 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +    public float HalfWidth;
Мы не используем публичные поля

2019-11-04 16:33 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +        }
Дублирование кода

2019-11-04 16:33 UTC, HolyMonkey commented on Assets/Scripts/GroundChecker.cs
> +   [SerializeField] private LayerMask _whatisGround; //слой, который принимаем в качестве нужного (Ground)
Откажись от комментариев

2019-11-04 16:33 UTC, HolyMonkey commented on Assets/Scripts/Item.cs
> +}
Класс не имеет смысла

2019-11-04 16:33 UTC, HolyMonkey commented on Assets/Scripts/Player.cs
> +public class  Player : MonoBehaviour
Раздели ответсвенности класса. Всё намешено в одно

2019-11-04 16:33 UTC, HolyMonkey commented on Assets/Scripts/UpralenieButton.cs
> +public class UpralenieButton : MonoBehaviour
Что за название?

2019-11-04 16:36 UTC, HolyMonkey commented
Код на отьебись. В следующий раз 10 раз пройдись прежде чем отправлять. Начни с приведение к общему знаменателю. Очень плохо если в одном компоненте всё сделано в одном стиле а в другом в совершенно ином. Сверься ещё раз с вот этим - https://trello.com/c/95Nrqbmf/60-%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D1%8B

2019-11-12 19:29 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +public class AirDrop : MonoBehaviour
Спорное название. Более общепринятое название всё-таки Spawner

2019-11-12 19:29 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +    public int ItemsCount { get; private set; }
Почему это свойством? И свойства идут после полей

2019-11-12 19:29 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +    [SerializeField] private GameObject _barrier;
_barrierPrefab или _barrierTemplate

2019-11-12 19:29 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +        return  i= rnd.Next(0,10);
Используй Unity Random

2019-11-12 19:29 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +    private int _itemsCountrand()
Метод не называются в таком стиле, всегда PascalCase и название должны быть по шаблону ГлаголСуществительное

2019-11-12 19:29 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +    void Start()
обязательно указывай private

2019-11-12 19:29 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +            Instantiate(_barrier, new Vector3(UnityEngine.Random.Range(transform.position.x - _halfWidth, transform.position.x + _halfWidth), transform.position.y, transform.position.z), Quaternion.i
Код дублируется

2019-11-12 19:29 UTC, HolyMonkey commented on Assets/Scripts/Buttons.cs
> +    void Update()
private

2019-11-12 19:29 UTC, HolyMonkey commented on Assets/Scripts/Buttons.cs
> +   private void Escape()
криво

2019-11-12 19:29 UTC, HolyMonkey commented on Assets/Scripts/InGameUI.cs
> +    }
Разделяй группы членов пустой строкой

2019-11-12 19:29 UTC, HolyMonkey commented on Assets/Scripts/InGameUI.cs
> +        }
Ты здесь пытаешься проверить собрал ли игрок все монетки на уровне?

2019-11-25 06:25 UTC, ap4ep commented on Assets/Scripts/Spawner.cs
>      private GroundChecker _groundchecker;
Разделить пустыми строками поля от метода и SerializeField
использовать верблюжий стиль именования переменных, например _groundChecker

2019-11-25 06:25 UTC, ap4ep commented on Assets/Scripts/Spawner.cs
>              CountDimonds += 1;
CountDimonds++;

2019-11-25 06:25 UTC, ap4ep commented on Assets/Scripts/Spawner.cs
>          float horizontal = Input.GetAxisRaw("Horizontal");
сделать полем

2019-11-25 06:25 UTC, ap4ep commented on Assets/Scripts/Spawner.cs
> +    }
Переделать в свойство с приватным сеттером

2019-11-25 06:25 UTC, ap4ep commented on Assets/Scripts/Mainmenu.cs
> +    private void Play()
разделить пустой строкой

2019-11-25 06:25 UTC, ap4ep commented on Assets/Scripts/InGameUI.cs
> +    private void Update()
разделить пустой строкой

2019-11-25 06:25 UTC, ap4ep commented on Assets/Scripts/GoldChecker.cs
> +   private void Update()
разделить пустой строкой, пробегись по всем файлам отдели методы от полей и свойств

2019-11-25 06:25 UTC, ap4ep commented on Assets/Scripts/Mainmenu.cs
>  public class Mainmenu : MonoBehaviour
MainMenu

2019-11-25 06:55 UTC, ap4ep commented on Assets/Scripts/InGameUI.cs
> +        _countDimonds.text = dimondsdif.ToString();
Так лучше не делать, надо через событие

2019-11-25 06:55 UTC, ap4ep commented on Assets/Scripts/Mainmenu.cs
> +    [SerializeField] private Animator Aboutanimator;
_aboutAnimator

2019-11-25 06:55 UTC, ap4ep commented on Assets/Scripts/Player.cs
>              transform.localScale = new Vector3(-1, 1, 1);
Движение вынести в отдельный метод, вместо transform.localScale, лучше использовать SpriteRenderer и его свойств flipY

2019-11-25 06:55 UTC, ap4ep commented on Assets/Scripts/Player.cs
>              collision.gameObject.SetActive(false);
Лучше все таки уничтожать объект, а не отключать его

2019-11-25 06:55 UTC, ap4ep commented on Assets/Scripts/InGameUI.cs
> +    private int dimondsdif;
_dimodDifference откажись от сокращений

2019-11-25 09:04 UTC, Benjail commented on Assets/Scripts/InGameUI.cs
> +    private int dimondsdif;
В последнем коммите у меня нет уже такого поля (dimondsdif)

2019-11-25 09:07 UTC, ap4ep commented on Assets/Scripts/InGameUI.cs
> +    private int dimondsdif;
Виноват

2019-11-25 09:28 UTC, Powertr1p commented on Assets/Scripts/AirDrop.cs
> +    [SerializeField] private int ItemsCount;
приватные поля должны начинаться с _ и с первое слово с маленькой буквы

2019-11-25 09:29 UTC, Powertr1p commented on Assets/Scripts/AirDrop.cs
> +    private int RandItemsCount()
Мы не сокращаем названия методов

2019-11-25 09:32 UTC, Powertr1p commented on Assets/Scripts/AirDrop.cs
> +        return i;
чтобы убрать неоднозначность между Random в юнити и Random в System, лучше отказаться от подключения неймпсейса System, так как мы его используем реже.

Помимо этого, можно записать в одну строчку: return Random.Range(0,10).

2019-11-25 09:33 UTC, Powertr1p commented on Assets/Scripts/AirDrop.cs
> +    }
можно убрать этот метод, сделав ItemCount через свойство {get; private set;}

2019-11-25 09:36 UTC, Powertr1p commented on Assets/Scripts/AirDrop.cs
> +        Instantiate(gameObject, new Vector3(UnityEngine.Random.Range(transform.position.x - _halfWidth, transform.position.x + _halfWidth), transform.position.y, transform.position.z), Quaternion.ide
Длинная строка, которая плохо читается. Здесь Random.Range() можно вынести в отдельную переменную: Vector3 objectRandomXPosition = Random.Range(transform.position.x - _halfWidth, transform.position.x + _halfWidth);

2019-11-25 09:40 UTC, Powertr1p commented on Assets/Scripts/GroundChecker.cs
> +   [SerializeField] private LayerMask _whatisGround;
Плохое название переменной

2019-11-25 09:41 UTC, Benjail commented on Assets/Scripts/GroundChecker.cs
> +   [SerializeField] private LayerMask _whatisGround;
Какой из трёх?_radius?

2019-11-25 09:41 UTC, Powertr1p commented on Assets/Scripts/Mainmenu.cs
> +    [SerializeField] private Animator Aboutanimator;
Что такое Aboutanimator? Неправильное название переменной.

2019-11-25 09:44 UTC, ap4ep commented on Assets/Scripts/AirDrop.cs
>      }
не нужный метод прям в старте Random.Range(), не понятно зачем уточнение UnityEngine

2019-11-25 09:44 UTC, ap4ep commented on Assets/Scripts/AirDrop.cs
> +    [SerializeField] private int ItemsCount;
_itemsCount

2019-11-25 09:44 UTC, ap4ep commented on Assets/Scripts/AirDrop.cs
> +    }
сделай свойство

2019-11-25 09:44 UTC, ap4ep commented on Assets/Scripts/Buttons.cs
>  }
Не нужный класс

2019-11-25 09:44 UTC, ap4ep commented on Assets/Scripts/InGameUI.cs
> +        _countDimonds.text = (_airDrop.GetItemsCount() - _spawner.GetCountDimonds()).ToString();
надо сделать через событие, нам каждый кадр обновлять значение ни к чему

2019-11-25 09:44 UTC, ap4ep commented on Assets/Scripts/Mainmenu.cs
>          Aboutanimator.SetBool("IsOpen", !Aboutanimator.GetBool("IsOpen"));
Все таки лучше явно указывать false\true

2019-11-25 09:44 UTC, ap4ep commented on Assets/Scripts/Spawner.cs
> +public class Spawner : MonoBehaviour
Название класса не соответствует его действиям

2019-11-25 09:44 UTC, ap4ep commented on Assets/Scripts/Tracking.cs
>          transform.position = Vector3.Lerp(transform.position, new Vector3(_gameObject.transform.position.x, _gameObject.transform.position.y+_marginY, transform.position.z),_speed*Time.deltaTime);
раздели пробелами + и *

2019-11-25 09:44 UTC, Powertr1p commented on Assets/Scripts/Mainmenu.cs
> +        SceneManager.LoadScene("Level 1");
У тебя постоянно идет вызов разных сцен и меню из разных классов, предлагаю вынести это в отдельных класс LevelLoader, к которому ты будешь обращаться для загрузки требуемой сцены.

2019-11-25 10:06 UTC, Powertr1p commented on Assets/Scripts/Spawner.cs
> +    [SerializeField] private int CountDimonds;
Приватные переменные должны начинаться с _ и с маленькой буквы

2019-11-25 10:07 UTC, Powertr1p commented on Assets/Scripts/Spawner.cs
> +    }
Можно переделать через свойство {get; private set}

2019-11-25 10:09 UTC, Powertr1p commented on Assets/Scripts/Spawner.cs
> +        if (collision.gameObject.CompareTag("Item"))
Надо отказываться от всего, что производит проверку по стрингу, так как легко ошибиться в регистре.

2019-11-25 10:10 UTC, Powertr1p commented on Assets/Scripts/Spawner.cs
> +    private GroundChecker _groundchecker;
_groundChecker

2019-11-25 10:13 UTC, Powertr1p commented on Assets/Scripts/Spawner.cs
> +            CountDimonds += 1;
Отказывайся от магических литералов, которые могут сбить с толку при чтении листинга. 
Лучше сделать через _countDiamonds++;

2019-11-25 10:14 UTC, Powertr1p commented on Assets/Scripts/Spawner.cs
> +        _rigidbody2D.velocity = new Vector2(horizontal* _speed, _rigidbody2D.velocity.y);
поставь пробел между horizontal и *

2019-11-25 10:16 UTC, Powertr1p commented on Assets/Scripts/Spawner.cs
> +        }
Можно выделить в удобочитаемый метод Movement();

2019-11-25 10:18 UTC, Powertr1p commented on Assets/Scripts/Tracking.cs
> +        transform.position = Vector3.Lerp(transform.position, new Vector3(_gameObject.transform.position.x, _gameObject.transform.position.y+_marginY, transform.position.z),_speed*Time.deltaTime);
Для удобочитаемости new Vector3(_gameObject.transform.position.x, _gameObject.transform.position.y+_marginY, transform.position.z) надо выделить в отдельную переменную

2019-11-25 10:18 UTC, Powertr1p reviewed
review from Powertrip

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/AirDrop.cs
> +    [SerializeField] private int ItemsCount;
Соблюдай нотацию

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/AirDrop.cs
> +    [SerializeField] private GameObject _item;
Сделай пустую строку между полем и методом

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/AirDrop.cs
> +    private int RandItemsCount()
Не используй сокращения

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/AirDrop.cs
> +        return i;
Возвращай сразу Random.Range(0, 10)

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/AirDrop.cs
> +    public int GetItemsCount()
Сделай лучше свойство ItemsCount, которое будет указывать на поле _itemsCount

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/AirDrop.cs
> +    private int RandItemsCount()
Лучше добавь Get к названию метода

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/AirDrop.cs
> +   private void Start()
Что с отступом?

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/AirDrop.cs
> +    public void InstantiateObject(GameObject gameObject)
Добавь пустую строку между методами

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/AirDrop.cs
> +   private void Start()
Добавь пустую строку между методами

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/AirDrop.cs
> +    [SerializeField] private GameObject _item;
Не понятно что за item, подумай над названием

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/AirDrop.cs
> +        Instantiate(gameObject, new Vector3(UnityEngine.Random.Range(transform.position.x - _halfWidth, transform.position.x + _halfWidth), transform.position.y, transform.position.z), Quaternion.ide
Вынеси получение позиции в метод

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/Buttons.cs
> +        private void Update()
Что с отступом?

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/Buttons.cs
> +public class Buttons : MonoBehaviour
Не совсем понимаю название во множественном числе, подумай над названием

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/GoldChecker.cs
> +   public bool IsGoldCollected()
Что с отступом?

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/GoldChecker.cs
> +   private void Update()
Что с отступом?

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/GoldChecker.cs
> +   private void Update()
Раздели методы пустой строкой

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/GroundChecker.cs
> +   [SerializeField] private LayerMask _whatisGround;
Подумай над названием переменной, лучше использовать что-то вроде _groundLayer

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/GroundChecker.cs
> +    public bool CheckGround()
Что с отступом?

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/GroundChecker.cs
> +    public bool CheckGround()
Раздели поля и метод пустой строкой

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/InGameUI.cs
> +        _countDimonds.text = (_airDrop.GetItemsCount() - _spawner.GetCountDimonds()).ToString();
Используй события

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/InGameUI.cs
> +    private void Update()
Раздели поля и метод пустой строкой

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/InGameUI.cs
> +public class InGameUI : MonoBehaviour
Подумай над названием

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/Mainmenu.cs
> +    [SerializeField] private Animator Aboutanimator;
Подумай над названием

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/Mainmenu.cs
> +    private void Play()
Раздели поля и метод пустой строкой

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/Mainmenu.cs
> +    private void About()
Раздели методы пустой строкой

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/Mainmenu.cs
> +    private void Exit()
Раздели методы пустой строкой

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/Mainmenu.cs
> +    private void About()
Подумай над названием

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/Spawner.cs
> +[RequireComponent (typeof(GroundChecker))]
Сделай пустую строку между using и RequireComponent

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/Spawner.cs
> +    [SerializeField] private int CountDimonds;
Соблюдай нотацию

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/Spawner.cs
> +    public int GetCountDimonds()
CountDimonds => _countDimonds будет лучше смотреться

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/Spawner.cs
> +    private void Update()
Отдели везде методы пустой строкой

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/Tracking.cs
> +    [SerializeField] private GameObject _gameObject;
Название переменной ничего не отражает

2019-11-25 10:58 UTC, Lexv0lk commented on Assets/Scripts/Tracking.cs
> +    private void Update()
Отдели пустой строкой

2019-11-25 12:30 UTC, Powertr1p commented on Assets/Scripts/GroundChecker.cs
> +   [SerializeField] private LayerMask _whatisGround;
Я не знаю почему выделилось 3 поля(( я говорил про _whatisGround. Тут лучше использовать что-то вроде _groundType.
Я понимаю, что ты использовал эту переменную, для прыжка, но если такое делают, то делают обычно булеву переменную _isGround. Когда персонаж на земле — она принимает значение true, а когда в воздухе или другой поверхности, где нельзя прыгать — false. И при попытке прыжка ты просто проверяешь true она или false.

2019-11-25 19:01 UTC, Powertr1p commented on Assets/Scripts/Spawner.cs
> +    [SerializeField] private int CountDimonds;
ошибка в слове "diamonds"

2019-11-25 19:07 UTC, Powertr1p commented on Assets/Scripts/Spawner.cs
> +public class Spawner : MonoBehaviour
Я не особо понимаю, что здесь происходит, если честно — у тебя класс Spawner, но при этом внутри него и передвижение и прыжки и подсчет бриллиантов. Если пользователь не играет за спавнер, чья цель двигаться и считать бриллианты — то надо разделять ответственности и переделать класс.

2019-11-25 19:10 UTC, Powertr1p reviewed
added some comments

2019-11-27 17:02 UTC, HolyMonkey requested changes

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +    [SerializeField] private int ItemsCount;
Согласен

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +    [SerializeField] private GameObject _item;
Согласен

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +    [SerializeField] private GameObject _item;
Согласен

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +    private int RandItemsCount()
Согласен

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +    private int RandItemsCount()
Согласен

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +        return i;
Согласен

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +    public int GetItemsCount()
Согласен

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +    public void InstantiateObject(GameObject gameObject)
Согласен

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +        Instantiate(gameObject, new Vector3(UnityEngine.Random.Range(transform.position.x - _halfWidth, transform.position.x + _halfWidth), transform.position.y, transform.position.z), Quaternion.ide
Лучше так: 

position + new Vector3(Random.Range(-_halwWidth, halfWidth, 0, 0);

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +        Instantiate(gameObject, new Vector3(UnityEngine.Random.Range(transform.position.x - _halfWidth, transform.position.x + _halfWidth), transform.position.y, transform.position.z), Quaternion.ide
Согласен

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +   private void Start()
Согласен

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/Buttons.cs
> +public class Buttons : MonoBehaviour
Во множественном числе нет ничего плохого. Но в данном случае действительно бесмыслено

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/GoldChecker.cs
> +   private void Update()
Согласен

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/GroundChecker.cs
> +   [SerializeField] private LayerMask _whatisGround;
_groundLayer хорошее название

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/InGameUI.cs
> +        _countDimonds.text = (_airDrop.GetItemsCount() - _spawner.GetCountDimonds()).ToString();
Верно

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/Mainmenu.cs
>  public class Mainmenu : MonoBehaviour
Верно

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/Mainmenu.cs
> +    [SerializeField] private Animator Aboutanimator;
Согласен

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/Spawner.cs
> +[RequireComponent (typeof(GroundChecker))]
Да

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/Spawner.cs
> +public class Spawner : MonoBehaviour
Верно

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/Spawner.cs
> +    [SerializeField] private int CountDimonds;
согласен

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/Spawner.cs
> +    private GroundChecker _groundchecker;
Верно

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/Spawner.cs
> +    public int GetCountDimonds()
Верно

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/Spawner.cs
> +        if (collision.gameObject.CompareTag("Item"))
Верно. Теги лучше вынести в константы в отдельный файл или же делать проверку по компоненту

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/Spawner.cs
> +            CountDimonds += 1;
Согласен

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/Spawner.cs
>          float horizontal = Input.GetAxisRaw("Horizontal");
Этого точно делать не стоит

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/Spawner.cs
> +        _rigidbody2D.velocity = new Vector2(horizontal* _speed, _rigidbody2D.velocity.y);
Верно

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/Spawner.cs
> +        }
Декомпозировать надо но не так

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/Tracking.cs
> +    [SerializeField] private GameObject _gameObject;
верно

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/Tracking.cs
>          transform.position = Vector3.Lerp(transform.position, new Vector3(_gameObject.transform.position.x, _gameObject.transform.position.y+_marginY, transform.position.z),_speed*Time.deltaTime);
верно

2019-11-27 17:02 UTC, HolyMonkey commented on Assets/Scripts/Tracking.cs
> +        transform.position = Vector3.Lerp(transform.position, new Vector3(_gameObject.transform.position.x, _gameObject.transform.position.y+_marginY, transform.position.z),_speed*Time.deltaTime);
Лучше в метод

2019-12-14 12:28 UTC, HolyMonkey requested changes

2019-12-14 12:28 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +    public int CountGold { get=>_countGold; private set=>_countGold=value;}
Замени на автореализуемое свойство

2019-12-14 12:28 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +        }
Отсортируй методы. Первые идут методы сообщений Unity (private Start например), потом публичные, потом приватные

2019-12-14 12:28 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +    private void Start()
Между методами нужны пробелы

2019-12-14 12:28 UTC, HolyMonkey commented on Assets/Scripts/AirDrop.cs
> +    public int CountGold { get=>_countGold; private set=>_countGold=value;}
SpawnedGold

2019-12-14 12:28 UTC, HolyMonkey commented on Assets/Scripts/MoveObject.cs
> +public class MoveObject : MonoBehaviour
Уточни название

2024-07-01 09:08 UTC, closed without merging